sudo: required
os:
  - linux

language: c++

before_install:
  - |
    echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    curl --silent https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/bazel.list" \
        -o Dir::Etc::sourceparts="-" \
        -o APT::Get::List-Cleanup="0"
    sudo apt-get install openjdk-8-jdk bazel

script:
  - |
    bazel \
        --output_baze=$HOME/.cache/bazel \
        --batch \
        --host_jvm_args=-Xmx500m \
        --host_jvm_args=-Xms500m \
        test \
        --config=ci \
        --experimental_repository_cache="$HOME/.bazel_repository_cache" \
        --local_resources=400,1,1.0 \
        --test_tag_filters=-dev \
        //...
